[package]
name = "surl_redirect_microservice"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
deadpool-postgres = "0.14.1"
dotenvy = "0.15.7"
governor = "0.10.1"
tokio = { version = "1.48.0", features = ["full"] }
tokio-postgres = "0.7.15"
tower = "0.5.2"
tower_governor = "0.8.0"
